print('Digite o valor de x1:')
x1 = float(input())
print('Digite o valor de x2:')
x2 = float(input())
print('Digite o valor de y1:')
y1 = float(input())
print('Digite o valor de y2')
y2 = float(input())

d1 = (x2-x1)*(x2-x1)+(y2-y1)*(y2-y1)
print(f'A distância entre os dois pontos é = {2:.f}'.format(d1))
